sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

before_install:
  # Disable XDebug
  - phpenv config-rm xdebug.ini

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=trunk
    - php: 7.0
      env: WP_VERSION=4.6.5
    - php: 7.0
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=trunk

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    composer global require "phpunit/phpunit=5.7.*"

script:
  - |
    # Run single-site unit tests:
    export WP_MULTISITE=0
    phpunit --exclude-group=ms-required

    # Run Multisite unit tests:
    export WP_MULTISITE=1
    phpunit --exclude-group=ms-excluded
